version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: .Dockerfile
    ports:
      - '3000:3000'

  proxy:
    build:
      context: ./proxy
      dockerfile: .Dockerfile
    ports:
      - '8787:8787'
    depends_on:
      - api
