version: '3.8'

services:
  api:
    container_name: tempo-sync-api
    build:
      context: ./api
      dockerfile: .Dockerfile
    expose:
      - '3000'

  proxy:
    container_name: tempo-sync-proxy
    build:
      context: ./proxy
      dockerfile: .Dockerfile
    expose:
      - '8787'
    depends_on:
      - api

  nginx:
    container_name: tempo-sync-nginx
    image: nginx:alpine
    ports:
      - '3001:3001'
      - '443:443'
      - '3000:3000'
      - '8787:8787'
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - proxy
      - api
